// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/v1/message.proto

package log_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     uint32                 `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        uint64                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          uint32                 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Crc           uint32                 `protobuf:"varint,8,opt,name=crc,proto3" json:"crc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Message) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Message) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Message) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Message) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

var File_api_v1_message_proto protoreflect.FileDescriptor

const file_api_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/message.proto\x12\x06log.v1\"\xc1\x01\n" +
	"\aMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x04 \x01(\rR\tpartition\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x04R\x06offset\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x12\n" +
	"\x04size\x18\a \x01(\rR\x04size\x12\x10\n" +
	"\x03crc\x18\b \x01(\rR\x03crcB%Z#github.com/Afrawles/Qute/api/log_v1b\x06proto3"

var (
	file_api_v1_message_proto_rawDescOnce sync.Once
	file_api_v1_message_proto_rawDescData []byte
)

func file_api_v1_message_proto_rawDescGZIP() []byte {
	file_api_v1_message_proto_rawDescOnce.Do(func() {
		file_api_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_message_proto_rawDesc), len(file_api_v1_message_proto_rawDesc)))
	})
	return file_api_v1_message_proto_rawDescData
}

var file_api_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_v1_message_proto_goTypes = []any{
	(*Message)(nil), // 0: log.v1.Message
}
var file_api_v1_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_message_proto_init() }
func file_api_v1_message_proto_init() {
	if File_api_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_message_proto_rawDesc), len(file_api_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_message_proto_goTypes,
		DependencyIndexes: file_api_v1_message_proto_depIdxs,
		MessageInfos:      file_api_v1_message_proto_msgTypes,
	}.Build()
	File_api_v1_message_proto = out.File
	file_api_v1_message_proto_goTypes = nil
	file_api_v1_message_proto_depIdxs = nil
}
